---

# config

- name: Ensure init.d script for update-daemon is enabled and runs
  service:
    name: tt-rss
    enabled: yes
    state: started
  become: true

- name: Ensure config.php is present
  template:
    src: config.php.j2
    dest: "{{  ttrss_install_path }}/config.php"
  
- name: "Ensure database is present"
  become_user: postgres
  postgresql_db: 
    name: "{{ ttrss_db_name }}"
    encoding: "{{ ttrss_db_encoding }}"
    lc_collate: "{{ ttrss_db_collate }}"
    lc_ctype: "{{ ttrss_db_ctype }}"
    template: template0
    owner: "{{ ttrss_db_user }}"

- name: Ensure db objects are created
  environment:
    PGPASSWORD: "{{ ttrss_db_password }}"
    PGUSER: "{{ ttrss_db_user }}"
    PGHOST: localhost
  command: psql -d "{{ttrss_db_name}}" -f "{{ ttrss_install_path }}/schema/ttrss_schema_pgsql.sql"
  args:
    creates: "{{ ttrss_install_path }}/config.php"

- name: "Ensure apache is configured"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    validate: "apachectl configtest"
  notify: Restart apache
  with_items:
    - { src: tt-rss.conf.j2, dest: /etc/apache2/sites-available/tt-rss.conf }
    - { src: php7.0-fpm.conf.j2, dest: /etc/apache2/conf-available/php7.0-fpm.conf }
  become: true`
    
- name: Ensure apache site is enabled
  command: /usr/sbin/a2ensite /etc/apache2/sites-available/tt-rss.conf
  register: result
  failed_when: result.rc != 0 and "already enabled" not in result.stdout
  changed_when: result.rc == 0 and "already enabled" not in result.stdout
  notify: Restart apache
  become: true