---

# config

- name: Reset permissions for tt-rss for www
  file:
    state: directory
    owner: www-data
    group: www-data
    recurse: yes
    path: "{{ ttrss_install_path }}/{{ item }}"
  with_items:
  - cache
  - feed-icons
  - lock
  become: true
  
- name: Create a new database with name 'ttrss'
  mysql_db:
    name: "{{ ttrss_db_name }}"
    state: present
    login_password: "{{ ttrss_db_passwd }}"
  become: true

- name: Import MySQL schema
  mysql_db:
    state: import
    name: "{{ ttrss_db_name }}"
    target: "{{ ttrss_install_path }}/schema/ttrss_schema_mysql.sql"
    login_password: "{{ ttrss_db_passwd }}"
  become: true

- name: Ensure config.php is present
  template:
    src: config.php.j2
    dest: "{{  ttrss_install_path }}/config.php"
  become: true

    
- name: "Ensure apache is configured"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  notify: Restart apache
  with_items:
    - { src: tt-rss.conf.j2, dest: /etc/apache2/sites-available/tt-rss.conf }
    - { src: php7.0-fpm.conf.j2, dest: /etc/apache2/conf-available/php7.0-fpm.conf }
  become: true

- name: Check the apache configuration
  command: apachectl -t
  register: apache_result
  ignore_errors: yes
  become: true

- name: Enable tt-rss site on apache
  command: a2ensite tt-rss
  args:
    creates: /etc/apache2/sites-enabled/tt-rss.conf
  notify: Restart apache
  become: true
