---

# installs

- name: Install pre-requisites
  apt: name={{ item }} state=present
  with_items:
    - "{{ dependencies }}"
  become: true

- name: Make tt-rss directory in www
  file: path="{{ ttrss_install_path }}" state=directory owner=www-data group=www-data mode=0644
  become: true
  
- name: "Get Tiny Tiny RSS Server"
  unarchive:
    src: "{{ ttrss_zip }}"
    dest: "{{ ttrss_install_path }}"
    remote_src: True
  become: true
  
- name: Reset permissions for tt-rss for www
  file:
    state: directory
    owner: www-data
    group: www-data
    recurse: yes
    path: "{{ ttrss_install_path }}/{{ item }}"
  with_items:
  - cache
  - feed-icons
  - lock