---

# installs

- name: Install pre-requisites
  apt: name={{ item }} state=present
  with_items:
    - "{{ dependencies }}"
  become: true

- name: "Git clone Tiny Tiny RSS Server code"
  git:
    repo: "{{ ttrss_git_repo }}"
    dest: "{{ ttrss_install_path }}"
    depth: 1
  become: true