---

# PRE-REQS

- name: Install pre-requisites
  apt: name={{ item }} state=present
  with_items:
    - "{{ dependencies }}"
  become: true

- name: Make tt-rss directory in www
  file: path="{{ ttrss_install_path }}" state=directory owner=www-data group=www-data mode=0755
  become: true
  
- name: "Get Tiny Tiny RSS Server"
  unarchive:
    src: "{{ ttrss_zip }}"
    dest: "{{ ttrss_install_path }}"
    remote_src: True
  become: true
