---

# installs

- name: Install pre-requisites
  apt: name={{ item }} state=present
  with_items:
    - "{{ dependencies }}"
  become: true

- name: Make tt-rss directory in www
  file: path=/var/www/tt-rss state=directory owner: www-data group: www-data mode: 0644
  
- name: "Get Tiny Tiny RSS Server"
  unarchive:
    src: "{{ ttrss_git_repo }}"
    dest: "{{ ttrss_install_path }}"
    remote_src: True
  become: true