---

# installs

- name: Install pre-requisites
  apt: name={{ item }} state=present
  with_items:
    - "{{ dependencies }}"
  become: true

- name: "Get Tiny Tiny RSS Server"
  unarchive:
    src: "{{ ttrss_git_repo }}"
    dest: "{{ ttrss_install_path }}"
    remote_src: True
  become: true